CREATE DATABASE "bms";
REVOKE ALL PRIVILEGES ON DATABASE "bms" FROM public;
CREATE USER bms_admin WITH PASSWORD 'pass' NOINHERIT NOSUPERUSER NOCREATEROLE NOCREATEDB;;
GRANT ALL PRIVILEGES ON DATABASE "bms" TO bms_admin;